name = "groktunes-api"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[vars]
ENVIRONMENT = "production"

[[ai]]
binding = "AI"

[build]
command = "npm run build"

[env.production]
workers_dev = false

[env.development]
workers_dev = true